name: Testing Actions

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: testing actions
        run: echo 'Begin Testing'
        shell: bash

  finish:
    runs-on: ubuntu-latest
    steps:
      - name: job end
        run: echo 'Job Finished'
        shell: bash
